// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace JellyMerge
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip buttonSound;
		public AudioClip swipeClip;
		public AudioClip squishClip;
		public AudioClip gameWinClip;
	}
}